### ISSUE TITLE
Add hydrology workshop announcement

### ISSUE THREAD

**Issue by njeffery** [IDEAS-Watersheds/ideas-watersheds.github.io#11]
PLOTRAN Workshop is Nov 6-9 and requires registration.  Time  sensitive.

**Comment by jd-moulton** [comment]
In the current setup of the site this activity would be just under _posts (and can link to update to the seminars page).   Existing short course posts are a good example.   We need a bit more information from Xingyuan though on the details of this entry.

**Comment by njeffery** [comment]
Addressed here:
https://github.com/IDEAS-Watersheds/ideas-watersheds.github.io/pull/12
